spigot:
  container_name: crownquest
  build: .
  volumes:
    - "./target/CrownQuest.jar:/spigot/plugins/CrownQuest.jar"
  ports:
    - "25565:25565"
  environment:
    - DENOMINATION_NAME=Crw
    - CROWNQUEST_ENV=production
    - CROWNQUEST_NODE_USERNAME=YOUR RPC USERNAME
    - CROWNQUEST_NODE_PASSWORD=YOUR RPC PASSWORD
    - CROWNQUEST_NODE_HOST=127.0.0.1
    - ADMIN_UUID=YOUR UUID
    - POSTGRES_PORT_5432_TCP_PORT=5432
  links:
    - redis
redis:
  image: redis
