spigot:
  container_name: crownquest
  build: .
  volumes:
    - "./target/CrownQuest.jar:/spigot/plugins/CrownQuest.jar"
  ports:
    - "25565:25565"
  environment:
    - DENOMINATION_NAME=Crw
    - BITQUEST_ENV=production
    - BITQUEST_NODE_USERNAME=YOUR RPC USERNAME
    - BITQUEST_NODE_PASSWORD=YOUR RPC PASSWORD
    - BITQUEST_NODE_HOST=127.0.0.1
    - ADMIN_UUID=YOUR UUID
  links:
    - redis
    - postgres
redis:
  image: redis
postgres:
  image: postgres
  environment:
    - POSTGRES_USER=crownquest
    - POSTGRES_PASSWORD=ORLY
