spigot:
  container_name: crownquest
  build: .
  volumes:
    - "./target/CrownQuest.jar:/spigot/plugins/CrownQuest.jar"
  ports:
    - "25565:25565"
  environment:
    - BLOCKCYPHER_CHAIN=crw/test3
    - DENOMINATION_NAME=TestCrws
  links:
    - redis
    - postgres
redis:
  image: redis
postgres:
  image: postgres
  environment:
    - POSTGRES_USER=crownquest
    - POSTGRES_PASSWORD=ORLY
