superuser: null
# commented until <walletAmount> gets a class getter
welcomeMessage:
   <bold><yellow>Welcome to CrownQuest, the server that runs on Crown! ^_^<reset>

   <yellow>Your CrownQuest address is <green><walletAddress>
   <yellow>Your balance is <green><walletAmount> SAT