# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The server that runs on Crown!
email: crownquest@crownquest.co
description: >
  Crownquest is a Survival style Minecraft server with a Crown-denominated economy: Players can buy, sell and trade items using CRW micropayments with a fully funcional Crown wallet you can send money to/from.
  To start playing, Connect to the following address using the PC Version of Minecraft:
  play.crownquest.co
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://crownquest.co" # the base hostname & protocol for your site
twitter_username: crownquestmc
github_username:  crownquest
facebook_username:  CrownQuestMC
reddit_username:  crownquest
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
collections:
  wiki:
    output: true
defaults:
  - scope:
      path: ""
      type: "wiki"
    values:
      layout: article